[package]
name = "cargo-plsfmt"
version = "0.1.0"
edition = "2024"

[dependencies]
prettyplease = "0.2.29"
syn = { version = "2.0.98", features = ["visit"] }
proc-macro2 = { version = "1.0.93", features = ["span-locations"] }

[dev-dependencies]
quote = "1.0.38"